name: Visual Regression Test
on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Generate storybook
        run: npm run build-storybook
      - name: Run new-expected
        run: npm run new-expected
      - name: Run actual
        run: npm run actual
      - name: Run storycap
        run: npm run storycap
